# 作業

練習以旋轉變換 + 平移變換來實現仿射變換

旋轉 45 度 + 縮放 0.5 倍 + 平移 (x+100, y-50)

In [1]:
import cv2
import time
import numpy as np

img = cv2.imread("lena.png")

Case 1: rotation > scale > shift

In [4]:
rows, cols = img.shape[:2]

# 取得旋轉矩陣
# getRotationMatrix2D(center, angle, scale)

matrix_rotate = cv2.getRotationMatrix2D((cols // 2, rows // 2), 45, 0.5)
print('Rotation Matrix')
print(martix_rotate)

# 取得平移矩陣
matrix_translate = np.array([[1, 0, 100], [0, 1, -50]], dtype=np.float32)
print('Translation Matrix')
print(matrix_translate)

# 旋轉
img_rotate = cv2.warpAffine(img, matrix_rotate, (cols, rows))

# 平移
img_rotate_trans = cv2.warpAffine(img_rotate, matrix_translate, (cols, rows))

# 組合 + 顯示圖片
img_show_rotate_trans = np.hstack((img, img_rotate, img_rotate_trans))

while True:
    cv2.imshow('Rotate 45, scale 0.5, Translate x+100, y-50', img_show_rotate_trans)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

Rotation Matrix
[[  0.35355339   0.35355339  74.98066402]
 [ -0.35355339   0.35355339 256.        ]]
Translation Matrix
[[  1.   0. 100.]
 [  0.   1. -50.]]


Case 2: any three point

In [26]:
rows, cols = img.shape[:2]

# 建立兩組三點
point_before = np.array([[50,50], [300,100], [200,300]], dtype=np.float32)
point_after = np.array([[80,80], [330,150], [300,300]], dtype=np.float32)

# 透過兩組三點的關係，取得 affine 矩陣
affine_matrix = cv2.getAffineTransform(point_before, point_after)

img_before = img.copy()
img_after = cv2.warpAffine(img, affine_matrix, (rows, cols))

# 在圖片上標記點和文字
for index, point in enumerate(point_before):
    point = tuple(map(int, point))

    cv2.circle(img_before, point, 3, (0, 255, 0), -1)
    cv2.putText(img_before, str(index), (point[0] + 5, point[1] + 5), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 1)

for index, point in enumerate(point_after):
    point = tuple(map(int, point))

    cv2.circle(img_after, point, 3, (0, 255, 0), -1)
    cv2.putText(img_after, str(index), (point[0] + 5, point[1] + 5), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 1)

# 組合 + 顯示圖片
img_show_affine = np.hstack((img_before, img_after))

while True:
    cv2.imshow("affine transformation", img_show_affine)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break